# Config for development only

sass:
  style: expanded

show_drafts: true
future:      true
unpublished: true

# Experimental config
#
# incremental building

#incremental: true

# livereload

livereload: true
